#Товары

GET http://127.0.0.1:8000/api/v1/products
Content-Type: application/json

POST http://127.0.0.1:8000/api/v1/products/
Content-Type:  application/json
Authorization: Token 2213ec395f32452440630054ed83460d80b05592

{
  "name": "Nokia N8",
  "price": 10000
}

PATCH http://127.0.0.1:8000/api/v1/products/1/
Content-Type:  application/json
Authorization: Token 2213ec395f32452440630054ed83460d80b05592

{
  "price": 20000
}

DELETE http://127.0.0.1:8000/api/v1/products/1/
Content-Type: application/json
Authorization: Token 2213ec395f32452440630054ed83460d80b05592

# Отзывы

GET http://127.0.0.1:8000/api/v1/product-reviews
Content-Type: application/json

POST http://127.0.0.1:8000/api/v1/product-reviews/
Content-Type:  application/json
Authorization: Token 2213ec395f32452440630054ed83460d80b05592

{
    "product": 1,
    "text": "Лучший телефон столетия!!",
    "rating": 5
}

PATCH http://127.0.0.1:8000/api/v1/products/1/
Content-Type:  application/json
Authorization: Token 2213ec395f32452440630054ed83460d80b05592

{
  "text": "Я передумал, не такойхороший",
  "rating": 3
}

DELETE http://127.0.0.1:8000/api/v1/product-reviews/1/
Content-Type: application/json
Authorization: Token 2213ec395f32452440630054ed83460d80b05592

# Заказы

GET http://127.0.0.1:8000/api/v1/orders
Content-Type: application/json

POST http://127.0.0.1:8000/api/v1/orders/
Content-Type:  application/json
Authorization: Token 2213ec395f32452440630054ed83460d80b05592

{
    "position": [
        {
            "quantity": 10,
            "product": 11
        },
        {
            "quantity": 10,
            "product": 12
        }
    ]
}

PATCH http://127.0.0.1:8000/api/v1/products/1/
Content-Type:  application/json
Authorization: Token 2213ec395f32452440630054ed83460d80b05592

{
  "status": "DONE"
}

DELETE http://127.0.0.1:8000/api/v1/products/1/
Content-Type: application/json
Authorization: Token 2213ec395f32452440630054ed83460d80b05592

# Коллекции

GET http://127.0.0.1:8000/api/v1/product-collections/
Content-Type: application/json

POST http://127.0.0.1:8000/api/v1/product-collections/
Content-Type:  application/json
Authorization: Token 2213ec395f32452440630054ed83460d80b05592

{
    "title": "test",
    "text": "test test",
    "products": [7, 8]
}


PATCH http://127.0.0.1:8000/api/v1/product-collections/1/
Content-Type:  application/json
Authorization: Token 2213ec395f32452440630054ed83460d80b05592

{
    "title": "34",
    "text": "test test",
    "products": [7,8]
}

DELETE http://127.0.0.1:8000/api/v1/product-collections/1/
Content-Type: application/json
Authorization: Token 2213ec395f32452440630054ed83460d80b05592