# Generated by Django 3.1.2 on 2021-06-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0002_auto_20210615_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='orders.Position', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_sum',
            field=models.FloatField(editable=False, verbose_name='Общая сумма'),
        ),
    ]
