# Generated by Django 3.1.2 on 2021-06-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210616_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_sum',
            field=models.FloatField(default=0, editable=False, verbose_name='Общая сумма'),
        ),
    ]
