# Generated by Django 3.1.2 on 2021-06-21 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210621_1737'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_auto_20210621_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=7, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='position',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='position', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='position',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Кол-во единиц'),
        ),
    ]
