# Generated by Django 3.1.2 on 2021-06-23 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210621_1737'),
        ('orders', '0005_auto_20210621_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='product',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='position', to='products.product', verbose_name='Товар'),
        ),
    ]
