# Generated by Django 3.1.2 on 2021-06-23 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210623_0917'),
        ('orders', '0006_auto_20210623_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='position',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='products.product', verbose_name='Товар'),
        ),
    ]
