# Generated by Django 3.1.2 on 2021-06-23 07:08

from django.db import migrations
from django.contrib.auth.models import User


def add_admin(app, schema_editor):
    if not User.objects.filter(username='admin').exists():
        user = User(
            username='admin',
            is_active=True,
            email='admin@admin.ru',
            is_staff=True,
            is_superuser=True
        )
        user.set_password('admin')
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210623_0917'),
    ]

    operations = [
        migrations.RunPython(add_admin)
    ]
