# Generated by Django 3.1.2 on 2021-06-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('collections_', '0002_auto_20210614_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='product',
        ),
        migrations.AddField(
            model_name='collection',
            name='products',
            field=models.ManyToManyField(related_name='collections', to='products.Product', verbose_name='Товар'),
        ),
    ]
