# Generated by Django 3.1.2 on 2021-06-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210621_1737'),
        ('collections_', '0003_auto_20210615_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='products',
            field=models.ManyToManyField(to='products.Product', verbose_name='Товар'),
        ),
    ]
